### ISSUE TITLE
Https on Azure

### ISSUE THREAD

**Issue by nojaf** [MicrosoftDX/Vorlonjs#191]
Hi, 

I'm trying to set up vorlon on Azure using https.
It's not working and I can't make heads or tails of it.
My error log in Monaco:
```
[warn] Consider changing the virtual directory '/' to map to your site's path 'site\wwwroot\mysite'
[warn] Virtual directories can be configured in the 'virtual directories' section on
[warn] https://manage.windowsazure.com/#Workspaces/WebsiteExtension/Website/mysite-vorlon/configure
[info] Click on http://mysite-vorlon.azurewebsites.net to open your site
Mon, 07 Sep 2015 17:16:41 GMT express-session deprecated req.secret; provide secret option at Scripts\vorlon.webServer.js:48:26
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Vorlon with SSL listening on port \\.\pipe\d601bb51-cbbd-4c86-b397-5af7cc8fb2b5
```

I did the deploy to azure button, uploaded my certificate files and changed the config.js.
So I would like to have https://vorlon.mysite.com up and running but it's not doing anything.

Any ideas?

Thanks,

nojaf

**Comment by deltakosh** [comment]
Hello, pulling in @meulta and @pierlag :)

**Comment by meulta** [comment]
Hello,

Did you follow the documentation on the readme file on the root the github repo ? :) https://github.com/MicrosoftDX/Vorlonjs/blob/development-0.0.16/README.md

**Comment by nojaf** [comment]
yup, that's the thing.

**Comment by meulta** [comment]
Can you give more information about your issue ? What is not working?
We need more to be able to help you.
Thanks :)

**Comment by pierlag** [comment]
is working if you use azure domain name like https://xxx.azurewebsites.net ?

**Comment by nojaf** [comment]
No, found a error page with HTTP Error 500.1001 - Internal Server Error
Logs aren't really saying anything.
```Tue, 08 Sep 2015 15:58:14 GMT express-session deprecated req.secret; provide secret option at Scripts\vorlon.webServer.js:48:26```

**Comment by meulta** [comment]
The deprecated message is on master (not causing any trouble though) and will be corrected on 0.0.16. 
This is not the issue.

I think the issue is not on the vorlon size but on the Azure configuration, can you give us more info about how you azure website is configured?
Thanks

**Comment by nojaf** [comment]
Hi, sorry for the delay. I didn't configure anything on Azure. I hit the 'deploy to azure' button, then it ran correctly. 
And I uploaded my certificates and changed the config.json file.

**Comment by deltakosh** [comment]
Is it a paid certificate? Did you check azure web sites log (WEB SERVER LOGGING + DETAILED ERROR MESSAGES + FAILED REQUEST TRACING)?

**Comment by nojaf** [comment]
Yes, I'm using a paid certificate indeed. Can't find anything in the logs. But I've only just enabled everything. I'll look again tomorrow.

**Comment by meulta** [comment]
Okay, give us anymore detail you can, we are not able to see where your problem is right now :/

**Comment by nojaf** [comment]
Not sure if any of this is helpful

In http/RawLogs/
```
#Software: Microsoft Internet Information Services 8.0
#Fields: date time s-sitename cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Cookie) cs(Referer) cs-host sc-status sc-substatus sc-win32-status sc-bytes cs-bytes time-taken
2015-09-20 12:23:00 SHELVE-VORLON GET / X-ARR-LOG-ID=cd59c3e1-d36d-4c3d-95cd-9b0fbb30ce0d 443 - 78.23.9.79 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/45.0.2454.93+Safari/537.36 _ga=GA1.2.455482739.1439927259 - vorlon.shelve.io 500 1001 2 449 971 45846
2015-09-20 12:23:28 SHELVE-VORLON GET /favicon.ico X-ARR-LOG-ID=5bb1a798-8be1-4929-8970-04bb0c17ee11 443 - 78.23.9.79 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/45.0.2454.93+Safari/537.36 _ga=GA1.2.455482739.1439927259;+ARRAffinity=f8d800d613e37b9f89703cfc947c140144eef518b7f515ac662995774ec65153 https://vorlon.shelve.io/ vorlon.shelve.io 500 1001 2 460 995 27726
2015-09-20 12:23:40 ~1SHELVE-VORLON GET /api/deployments/ X-ARR-LOG-ID=c22a20b1-d846-4da8-8330-f2266efda518 443 - 70.37.57.58 Portal-Exp/5.12.0.126+(Websites)+Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML%2C+like+Gecko)+Chrome/45.0.2454.93+Safari/537.36 - - shelve-vorlon.scm.azurewebsites.net 200 0 0 1306 1346 14272
2015-09-20 12:24:11 SHELVE-VORLON GET / X-ARR-LOG-ID=4885f198-9784-45cd-a4a0-1c0f99964ea2 80 - 78.23.9.79 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/45.0.2454.93+Safari/537.36 _ga=GA1.2.455482739.1439927259;+ARRAffinity=f8d800d613e37b9f89703cfc947c140144eef518b7f515ac662995774ec65153 - vorlon.shelve.io 500 1001 2 460 918 25909
```

Am I missing some sort of port forwarding? 1337 to https?

Errorpage in DetailedErrors/
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS Detailed Error - 500.1013 - Internal Server Error</title> 
<style type="text/css"> 
<!-- 
body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;} 
code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;} 
.config_source code{font-size:.8em;color:#000000;} 
pre{margin:0;font-size:1.4em;word-wrap:break-word;} 
ul,ol{margin:10px 0 10px 5px;} 
ul.first,ol.first{margin-top:5px;} 
fieldset{padding:0 15px 10px 15px;word-break:break-all;} 
.summary-container fieldset{padding-bottom:5px;margin-top:4px;} 
legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;} 
legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px; 
font-weight:bold;font-size:1em;} 
a:link,a:visited{color:#007EFF;font-weight:bold;} 
a:hover{text-decoration:none;} 
h1{font-size:2.4em;margin:0;color:#FFF;} 
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;} 
h4{font-size:1.2em;margin:10px 0 5px 0; 
}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif; 
color:#FFF;background-color:#5C87B2; 
}#content{margin:0 0 0 2%;position:relative;} 
.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;} 
.content-container p{margin:0 0 10px 0; 
}#details-left{width:35%;float:left;margin-right:2%; 
}#details-right{width:63%;float:left;overflow:hidden; 
}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF; 
background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal; 
font-size:1em;color:#FFF;text-align:right; 
}#server_version p{margin:5px 0;} 
table{margin:4px 0 4px 0;width:100%;border:none;} 
td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;} 
th{width:30%;text-align:right;padding-right:2%;font-weight:bold;} 
thead th{background-color:#ebebeb;width:25%; 
}#details-right th{width:20%;} 
table tr.alt td,table tr.alt th{} 
.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;} 
.clear{clear:both;} 
.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;} 
--> 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 500.1013 - Internal Server Error</h3> 
<h4>The page cannot be displayed because an internal server error has occurred.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x0000006d</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://shelve-vorlon:80/server.js</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\Server\server.js</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,1013,0x0000006d,9200">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 
  
 
</fieldset> 
</div> 
</div> 
</body> 
</html> 
```

Perhaps if somebody wants to take a look at the Azure side of the website. I could provide temporary access to the site.

**Comment by meulta** [comment]
Thanks for your info. @pierlag does that help you ?

**Comment by nojaf** [comment]
Hi guys, I'm dropping the ssl setting and running on plain old http.
I can't provide you the info you need so let's not waste any more time on this ;)
