### ISSUE TITLE
Installation errors on Mac OS X El Capitan

### ISSUE THREAD

**Issue by nhoizey** [MicrosoftDX/Vorlonjs#286]
I tried to install Vorlon using `sudo npm i -g vorlon` on my Mac OS X El Capitan running Node 4.2.1 and got these errors:

```
$ sudo npm i -g vorlon
/usr/local/Cellar/node/4.2.1/bin/vorlon -> /usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/bin/vorlon

> bufferutil@1.1.0 install /usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/nhoizey/.node-gyp/4.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp"
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd
      argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: 
      candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:210:7: note: 
      candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:210:7: note: 
      candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:214:13: note: 
      candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:326:13: note: 
      candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/Cellar/node/4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1

> utf-8-validate@1.1.0 install /usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/nhoizey/.node-gyp/4.2.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp"
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd
      argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: 
      candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/validation.cc:15:
../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:210:7: note: 
      candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:210:7: note: 
      candidate constructor (the implicit move constructor) not viable: no known conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:214:13: note: 
      candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:326:13: note: 
      candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/validation.cc:15:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/validation.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:221:5: error: 
      assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate/.node-gyp/4.2.1/include/node/v8.h:180:37: note: 
      expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/Cellar/node/4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/Cellar/node/4.2.1/lib/node_modules/vorlon/node_modules/utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
/usr/local/Cellar/node/4.2.1/lib
└─┬ vorlon@0.1.0 
  ├─┬ body-parser@1.12.4 
  │ ├── bytes@1.0.0 
  │ ├── content-type@1.0.1 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ ├── depd@1.0.1 
  │ ├── iconv-lite@0.4.8 
  │ ├─┬ on-finished@2.2.1 
  │ │ └── ee-first@1.1.0 
  │ ├── qs@2.4.2 
  │ ├─┬ raw-body@2.0.2 
  │ │ └── bytes@2.1.0 
  │ └─┬ type-is@1.6.10 
  │   ├── media-typer@0.3.0 
  │   └─┬ mime-types@2.1.8 
  │     └── mime-db@1.20.0 
  ├── colors@1.1.2 
  ├─┬ cookie-parser@1.3.5 
  │ ├── cookie@0.1.3 
  │ └── cookie-signature@1.0.6 
  ├── cookieparser@0.1.0 
  ├─┬ express@4.12.4 
  │ ├─┬ accepts@1.2.13 
  │ │ └── negotiator@0.5.3 
  │ ├── content-disposition@0.5.0 
  │ ├── cookie@0.1.2 
  │ ├── escape-html@1.0.1 
  │ ├─┬ etag@1.6.0 
  │ │ └── crc@3.2.1 
  │ ├── finalhandler@0.3.6 
  │ ├── fresh@0.2.4 
  │ ├── merge-descriptors@1.0.0 
  │ ├── methods@1.1.1 
  │ ├── parseurl@1.3.0 
  │ ├── path-to-regexp@0.1.3 
  │ ├─┬ proxy-addr@1.0.10 
  │ │ ├── forwarded@0.1.0 
  │ │ └── ipaddr.js@1.0.5 
  │ ├── range-parser@1.0.3 
  │ ├─┬ send@0.12.3 
  │ │ ├── destroy@1.0.3 
  │ │ └── mime@1.3.4 
  │ ├── serve-static@1.9.3 
  │ ├── utils-merge@1.0.0 
  │ └── vary@1.0.1 
  ├─┬ express-session@1.11.3 
  │ ├── crc@3.3.0 
  │ ├── on-headers@1.0.1 
  │ └─┬ uid-safe@2.0.0 
  │   └── base64-url@1.2.1 
  ├─┬ fakeredis@0.3.4 
  │ └── redis@2.1.0 
  ├─┬ favicon@0.0.2 
  │ └─┬ request@2.67.0 
  │   ├── aws-sign2@0.6.0 
  │   ├── bl@1.0.0 
  │   ├── caseless@0.11.0 
  │   ├─┬ combined-stream@1.0.5 
  │   │ └── delayed-stream@1.0.0 
  │   ├── extend@3.0.0 
  │   ├── forever-agent@0.6.1 
  │   ├─┬ form-data@1.0.0-rc3 
  │   │ └── async@1.5.0 
  │   ├─┬ har-validator@2.0.3 
  │   │ ├─┬ chalk@1.1.1 
  │   │ │ ├── ansi-styles@2.1.0 
  │   │ │ ├── escape-string-regexp@1.0.4 
  │   │ │ ├─┬ has-ansi@2.0.0 
  │   │ │ │ └── ansi-regex@2.0.0 
  │   │ │ ├── strip-ansi@3.0.0 
  │   │ │ └── supports-color@2.0.0 
  │   │ ├─┬ commander@2.9.0 
  │   │ │ └── graceful-readlink@1.0.1 
  │   │ ├─┬ is-my-json-valid@2.12.3 
  │   │ │ ├── generate-function@2.0.0 
  │   │ │ ├─┬ generate-object-property@1.2.0 
  │   │ │ │ └── is-property@1.0.2 
  │   │ │ ├── jsonpointer@2.0.0 
  │   │ │ └── xtend@4.0.1 
  │   │ └─┬ pinkie-promise@2.0.0 
  │   │   └── pinkie@2.0.1 
  │   ├─┬ hawk@3.1.2 
  │   │ ├── boom@2.10.1 
  │   │ ├── cryptiles@2.0.5 
  │   │ ├── hoek@2.16.3 
  │   │ └── sntp@1.0.9 
  │   ├─┬ http-signature@1.1.0 
  │   │ ├── assert-plus@0.1.5 
  │   │ ├─┬ jsprim@1.2.2 
  │   │ │ ├── extsprintf@1.0.2 
  │   │ │ ├── json-schema@0.2.2 
  │   │ │ └── verror@1.3.6 
  │   │ └─┬ sshpk@1.7.1 
  │   │   ├── asn1@0.2.3 
  │   │   ├── assert-plus@0.2.0 
  │   │   ├── dashdash@1.10.1 
  │   │   ├── ecc-jsbn@0.1.1 
  │   │   ├── jodid25519@1.0.2 
  │   │   ├── jsbn@0.1.0 
  │   │   └── tweetnacl@0.13.2 
  │   ├── is-typedarray@1.0.0 
  │   ├── json-stringify-safe@5.0.1 
  │   ├── node-uuid@1.4.7 
  │   ├── oauth-sign@0.8.0 
  │   ├── qs@5.2.0 
  │   ├── stringstream@0.0.5 
  │   ├── tough-cookie@2.2.1 
  │   └── tunnel-agent@0.4.2 
  ├─┬ http-proxy@1.11.3 
  │ ├── eventemitter3@1.1.1 
  │ └── requires-port@0.0.1 
  ├─┬ jade@1.9.2 
  │ ├── character-parser@1.2.1 
  │ ├── commander@2.6.0 
  │ ├─┬ constantinople@3.0.2 
  │ │ └── acorn@2.6.4 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ transformers@2.1.0 
  │ │ ├─┬ css@1.0.8 
  │ │ │ ├── css-parse@1.0.4 
  │ │ │ └── css-stringify@1.0.5 
  │ │ ├─┬ promise@2.0.0 
  │ │ │ └── is-promise@1.0.1 
  │ │ └─┬ uglify-js@2.2.5 
  │ │   └─┬ optimist@0.3.7 
  │ │     └── wordwrap@0.0.3 
  │ ├── void-elements@2.0.1 
  │ └─┬ with@4.0.3 
  │   ├── acorn@1.2.2 
  │   └── acorn-globals@1.0.9 
  ├── json@9.0.3 
  ├── method-override@2.3.4 
  ├─┬ multer@0.1.8 
  │ ├─┬ busboy@0.2.12 
  │ │ ├─┬ dicer@0.2.5 
  │ │ │ ├── readable-stream@1.1.13 
  │ │ │ └── streamsearch@0.1.2 
  │ │ └─┬ readable-stream@1.1.13 
  │ │   ├── core-util-is@1.0.2 
  │ │   └── string_decoder@0.10.31 
  │ ├── mkdirp@0.3.5 
  │ ├── qs@1.2.2 
  │ └─┬ type-is@1.5.7 
  │   └─┬ mime-types@2.0.14 
  │     └── mime-db@1.12.0 
  ├─┬ passport@0.2.2 
  │ ├── passport-strategy@1.0.0 
  │ └── pause@0.0.1 
  ├── passport-local@1.0.0 
  ├─┬ passport-twitter@1.0.3 
  │ ├─┬ passport-oauth1@1.0.1 
  │ │ └── oauth@0.9.14 
  │ └─┬ xtraverse@0.1.0 
  │   └── xmldom@0.1.19 
  ├── redis@0.12.1 
  ├─┬ socket.io@1.3.6 
  │ ├─┬ debug@2.1.0 
  │ │ └── ms@0.6.2 
  │ ├─┬ engine.io@1.5.2 
  │ │ ├── base64id@0.1.0 
  │ │ ├─┬ debug@1.0.3 
  │ │ │ └── ms@0.6.2 
  │ │ ├─┬ engine.io-parser@1.2.1 
  │ │ │ ├── after@0.8.1 
  │ │ │ ├── arraybuffer.slice@0.0.6 
  │ │ │ ├── base64-arraybuffer@0.1.2 
  │ │ │ ├── blob@0.0.2 
  │ │ │ ├── has-binary@0.1.5 
  │ │ │ └── utf8@2.0.0 
  │ │ └─┬ ws@0.7.2 
  │ │   ├── options@0.0.6 
  │ │   └── ultron@1.0.2 
  │ ├─┬ has-binary-data@0.1.3 
  │ │ └── isarray@0.0.1 
  │ ├─┬ socket.io-adapter@0.3.1 
  │ │ ├─┬ debug@1.0.2 
  │ │ │ └── ms@0.6.2 
  │ │ ├── object-keys@1.0.1 
  │ │ └─┬ socket.io-parser@2.2.2 
  │ │   └── debug@0.7.4 
  │ ├─┬ socket.io-client@1.3.6 
  │ │ ├── backo2@1.0.2 
  │ │ ├── component-bind@1.0.0 
  │ │ ├── component-emitter@1.1.2 
  │ │ ├── debug@0.7.4 
  │ │ ├─┬ engine.io-client@1.5.2 
  │ │ │ ├── component-inherit@0.0.3 
  │ │ │ ├─┬ debug@1.0.4 
  │ │ │ │ └── ms@0.6.2 
  │ │ │ ├─┬ has-cors@1.0.3 
  │ │ │ │ └── global@2.0.1 
  │ │ │ ├── parsejson@0.0.1 
  │ │ │ ├── parseqs@0.0.2 
  │ │ │ ├── parseuri@0.0.4 
  │ │ │ └── xmlhttprequest@1.5.0 
  │ │ ├── has-binary@0.1.6 
  │ │ ├── indexof@0.0.1 
  │ │ ├── object-component@0.0.3 
  │ │ ├─┬ parseuri@0.0.2 
  │ │ │ └─┬ better-assert@1.0.2 
  │ │ │   └── callsite@1.0.0 
  │ │ └── to-array@0.1.3 
  │ └─┬ socket.io-parser@2.2.4 
  │   ├── benchmark@1.0.0 
  │   ├── debug@0.7.4 
  │   └── json3@3.2.6 
  ├─┬ socket.io-redis@0.1.4 
  │ ├── debug@0.7.4 
  │ ├─┬ msgpack-js@0.3.0 
  │ │ └─┬ bops@0.0.7 
  │ │   ├── base64-js@0.0.2 
  │ │   └── to-utf8@0.0.1 
  │ ├── redis@0.10.1 
  │ └── uid2@0.0.3 
  ├─┬ stylus@0.50.0 
  │ ├── css-parse@1.7.0 
  │ ├─┬ glob@3.2.11 
  │ │ ├── inherits@2.0.1 
  │ │ └─┬ minimatch@0.3.0 
  │ │   ├── lru-cache@2.7.3 
  │ │   └── sigmund@1.0.1 
  │ ├── mkdirp@0.3.5 
  │ ├── sax@0.5.8 
  │ └─┬ source-map@0.1.43 
  │   └── amdefine@1.0.0 
  ├─┬ winston@1.0.2 
  │ ├── async@1.0.0 
  │ ├── colors@1.0.3 
  │ ├── cycle@1.0.3 
  │ ├── eyes@0.1.8 
  │ ├── isstream@0.1.2 
  │ ├── pkginfo@0.3.1 
  │ └── stack-trace@0.0.9 
  ├─┬ winston-azure@0.0.4 
  │ └─┬ azure-storage@0.7.0 
  │   ├── browserify-mime@1.2.9 
  │   ├── extend@1.2.1 
  │   ├─┬ readable-stream@2.0.5 
  │   │ ├── process-nextick-args@1.0.6 
  │   │ └── util-deprecate@1.0.2 
  │   ├─┬ request@2.57.0 
  │   │ ├── aws-sign2@0.5.0 
  │   │ ├─┬ bl@0.9.4 
  │   │ │ └── readable-stream@1.0.33 
  │   │ ├── caseless@0.10.0 
  │   │ ├─┬ form-data@0.2.0 
  │   │ │ ├── async@0.9.2 
  │   │ │ └─┬ combined-stream@0.0.7 
  │   │ │   └── delayed-stream@0.0.5 
  │   │ ├─┬ har-validator@1.8.0 
  │   │ │ └── bluebird@2.10.2 
  │   │ ├── hawk@2.3.1 
  │   │ ├─┬ http-signature@0.11.0 
  │   │ │ ├── asn1@0.1.11 
  │   │ │ └── ctype@0.5.3 
  │   │ ├─┬ mime-types@2.0.14 
  │   │ │ └── mime-db@1.12.0 
  │   │ └── qs@3.1.0 
  │   ├── underscore@1.4.4 
  │   ├── validator@3.22.2 
  │   ├─┬ xml2js@0.2.7 
  │   │ └── sax@0.5.2 
  │   └── xmlbuilder@0.4.3 
  ├─┬ winston-logs-display@0.1.1 
  │ └─┬ winston@0.8.3 
  │   ├── async@0.2.10 
  │   └── colors@0.6.2 
  └── xmlhttprequest@1.7.0 
```

Then, running Vorlon seems to work anyway.

**Comment by meulta** [comment]
Hello,

There is an issue due to socket.io and the fact that it uses node-gyp to rebuild some dependencies...
You can read more about this here : https://github.com/nodejs/node-gyp/issues/734
Apparently it is related to a xcode config...

Hope this helps

**Comment by nhoizey** [comment]
This issue on node-gyp was fixed with installing XCode 7. I have XCode 7.2…

**Comment by meulta** [comment]
Yep I was not clear enough, there is somehow a config issue that node-gyp does not like. You can find plenty of different issues about this...
Unfortunately we do not have anyway to fix this on our side...

**Comment by nhoizey** [comment]
Ok
