### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by dolezel** [MicrosoftDX/Vorlonjs#349]
When enabling authentication ( http://vorlonjs.com/documentation/#configure-authentication ), server is throwing error:
```
TypeError: Cannot read property 'baseURL' of undefined
    at Dashboard.login (/srv/vorlon/node_modules/vorlon/Server/Scripts/vorlon.dashboard.js:59:62)
    at Layer.handle [as handle_request] (/srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/layer.js:82:5)
    at next (/srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/layer.js:82:5)
    at /srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/index.js:321:12)
    at next (/srv/vorlon/node_modules/vorlon/node_modules/express/lib/router/index.js:261:10)
    at SessionStrategy.strategy.pass (/srv/vorlon/node_modules/vorlon/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at SessionStrategy.authenticate (/srv/vorlon/node_modules/vorlon/node_modules/passport/lib/strategies/session.js:67:10)
```

**Comment by saurabhkirtani** [comment]
+1

**Comment by meulta** [comment]
Yep, should be in the new version this week ;)
