### ISSUE TITLE
One click deployment to Azure not working

### ISSUE THREAD

**Issue by deepak2016** [MicrosoftDX/Vorlonjs#383]
Getting errors while deploying. 
Resource group and site names are getting created correctly, verified it from Azure portal. 
But deployment is failing consistently. Is there any work around for this ? 
Error logs: 

Command: deploy.cmd
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Start script "./Server/server.js" from package.json is not found.
Missing server.js/app.js files, web.config is not generated
Looking for app.js/server.js under site root.
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 4.4.7.
Selected npm version 2.15.8
npm WARN package.json vorlon@0.4.0 No repository field.
npm WARN package.json vorlon@0.4.0 No license field.

> vorlon@0.4.0 prepublish D:\home\site\wwwroot
> npm run build

> vorlon@0.4.0 build D:\home\site\wwwroot
> node disclaimer.js && npm run build-all

Building vorlon.js...
Please ignore errors regarding Python and socket.io. This is due to a known issue with socket.io. More info here: https://github.com/socketio/socket.io/issues/1151

> vorlon@0.4.0 build-all D:\home\site\wwwroot
> gulp --gulpfile=./gulpfile.js

module.js:327
    throw err;

**Comment by deepak2016** [comment]
Following is the deployment error: 
Deployment Error
Repository 'GetSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (403) Forbidden.
 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__78.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<GetSettingAsync>d__4d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<GetSiteSourceControl>d__1.MoveNext().

**Comment by tricki** [comment]
I have the same problem, am getting the following error in the Activity Log:

`npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path D:\local\AppData\npm-cache\source-map\0.5.6\package.tgz.2145970134
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'D:\local\AppData\npm-cache\source-map\0.5.6\package.tgz.2145970134' -> 'D:\local\AppData\npm-cache\source-map\0.5.6\package.tgz'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'D:\local\AppData\npm-cache\source-map\0.5.6\package.tgz.2145970134' -> 'D:\local\AppData\npm-cache\source-map\0.5.6\package.tgz']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'D:\\local\\AppData\\npm-cache\\source-map\\0.5.6\\package.tgz.2145970134',
npm ERR!   dest: 'D:\\local\\AppData\\npm-cache\\source-map\\0.5.6\\package.tgz',
npm ERR!   parent: 'gulp-typescript' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
Thread was being aborted.
Thread was being aborted.`

**Comment by AlexeyKor** [comment]
I am getting the same problem.

**Comment by meulta** [comment]
Working on that :)

**Comment by meulta** [comment]
Can you try again?
