### ISSUE TITLE
With --config allow relative paths for crt and key

### ISSUE THREAD

**Issue by philjones88** [MicrosoftDX/Vorlonjs#413]
When you do:

`vorlon --config config.json`

Where:

```json
{
    "includeSocketIO": true,
    "useSSLAzure": false,
    "useSSL": true,
    "SSLkey": "server.key",
    "SSLcert": "server.crt"
}
```

It ends up trying to find the crt file still inside the node_modules folder NOT inside the folder where the `config.json` file is!

```
$ vorlon --config config.json
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/vorlon/Server/server.key'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at new HttpConfig (/usr/local/lib/node_modules/vorlon/Server/config/vorlon.httpconfig.js:19:29)
    at new DefaultContext (/usr/local/lib/node_modules/vorlon/Server/config/vorlon.servercontext.js:110:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/vorlon/Server/server.js:8:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by meulta** [comment]
Ah good catch!
You can copy paste the key files from the repo and paste them in the expected folder.

I think we have an issue with the package, this will only be a temporary fix
