### ISSUE TITLE
Can't run the "npm install" command

### ISSUE THREAD

**Issue by cubitouch** [MicrosoftDX/Vorlonjs#91]
I have the following npm-debug.log file when I run the "npm install" command:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose readDependencies loading dependencies from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\package.json
5 warn package.json vorlon@0.0.14 No repository field.
6 warn package.json vorlon@0.0.14 No license field.
7 verbose install where, deps [ 'C:\\Users\\HCA\\Documents\\GitHub\\vorlonjs\\Vorlonjs',
7 verbose install   [ 'xmlhttprequest',
7 verbose install     'body-parser',
7 verbose install     'cookieparser',
7 verbose install     'express',
7 verbose install     'express-session',
7 verbose install     'fakeredis',
7 verbose install     'favicon',
7 verbose install     'jade',
7 verbose install     'json',
7 verbose install     'logger',
7 verbose install     'multer',
7 verbose install     'passport',
7 verbose install     'passport-local',
7 verbose install     'redis',
7 verbose install     'socket.io',
7 verbose install     'socket.io-redis',
7 verbose install     'stylus',
7 verbose install     'winston',
7 verbose install     'winston-azure',
7 verbose install     'winston-logs-display',
7 verbose install     'gulp',
7 verbose install     'gulp-concat',
7 verbose install     'gulp-filter',
7 verbose install     'gulp-less',
7 verbose install     'gulp-rename',
7 verbose install     'gulp-sourcemaps',
7 verbose install     'gulp-typescript',
7 verbose install     'gulp-uglify',
7 verbose install     'gulp-util',
7 verbose install     'gulp-webserver',
7 verbose install     'merge2',
7 verbose install     'through' ] ]
8 verbose install where, peers [ 'C:\\Users\\HCA\\Documents\\GitHub\\vorlonjs\\Vorlonjs', [] ]
9 verbose installManyTop reading for lifecycle C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\package.json
10 info preinstall vorlon@0.0.14
11 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\ansi-regex\package.json
12 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\body-parser\package.json
13 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\cookieparser\package.json
14 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\express\package.json
15 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\express-session\package.json
16 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\fakeredis\package.json
17 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\favicon\package.json
18 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp\package.json
19 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-concat\package.json
20 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-filter\package.json
21 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-less\package.json
22 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-rename\package.json
23 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-sourcemaps\package.json
24 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-typescript\package.json
25 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-uglify\package.json
26 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-util\package.json
27 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-webserver\package.json
28 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\jade\package.json
29 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\json\package.json
30 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\lodash._basecopy\package.json
31 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\logger\package.json
32 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\merge2\package.json
33 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\multer\package.json
34 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\passport\package.json
35 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\passport-local\package.json
36 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\redis\package.json
37 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\socket.io\package.json
38 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\socket.io-redis\package.json
39 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\stylus\package.json
40 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\through\package.json
41 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\winston\package.json
42 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\winston-azure\package.json
43 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\winston-logs-display\package.json
44 verbose installManyTop reading scoped package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\xmlhttprequest\package.json
45 info package.json fakeredis@0.3.1 No license field.
46 info package.json favicon@0.0.2 No license field.
47 info package.json gulp-concat@2.5.2 No license field.
48 info package.json gulp-rename@1.2.2 No license field.
49 info package.json gulp-util@2.2.20 No license field.
50 info package.json json@9.0.3 No license field.
51 info package.json logger@0.0.1 No repository field.
52 info package.json logger@0.0.1 No license field.
53 info package.json merge2@0.3.5 No license field.
54 info package.json passport-local@1.0.0 No license field.
55 info package.json redis@0.12.1 No license field.
56 info package.json socket.io@1.3.5 No license field.
57 info package.json socket.io-redis@0.1.4 No license field.
58 info package.json winston@0.9.0 No license field.
59 info package.json winston-azure@0.0.4 No license field.
60 info package.json xmlhttprequest@1.7.0 No license field.
61 verbose readDependencies loading dependencies from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\package.json
62 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\ansi-regex\package.json
63 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\body-parser\package.json
64 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\cookieparser\package.json
65 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\express\package.json
66 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\express-session\package.json
67 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\fakeredis\package.json
68 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\favicon\package.json
69 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp\package.json
70 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-concat\package.json
71 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-filter\package.json
72 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-less\package.json
73 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-rename\package.json
74 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-sourcemaps\package.json
75 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-typescript\package.json
76 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-uglify\package.json
77 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-util\package.json
78 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\gulp-webserver\package.json
79 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\jade\package.json
80 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\json\package.json
81 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\lodash._basecopy\package.json
82 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\logger\package.json
83 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\merge2\package.json
84 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\multer\package.json
85 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\passport\package.json
86 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\passport-local\package.json
87 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\redis\package.json
88 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\socket.io\package.json
89 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\socket.io-redis\package.json
90 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\stylus\package.json
91 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\through\package.json
92 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\winston\package.json
93 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\winston-azure\package.json
94 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\winston-logs-display\package.json
95 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\xmlhttprequest\package.json
96 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\.bin\gulp\package.json
97 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\.bin\gulp.cmd\package.json
98 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\.bin\json\package.json
99 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\.bin\json.cmd\package.json
100 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\.bin\stylus\package.json
101 verbose targetResolver reading package data from C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\.bin\stylus.cmd\package.json
102 verbose already installed skipping passport@^0.2.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
103 verbose already installed skipping passport-local@^1.0.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
104 verbose already installed skipping redis@^0.12.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
105 verbose already installed skipping socket.io@^1.3.5 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
106 verbose already installed skipping socket.io-redis@^0.1.4 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
107 verbose already installed skipping stylus@^0.50.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
108 verbose already installed skipping winston@^0.9.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
109 verbose already installed skipping winston-azure@0.0.4 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
110 verbose already installed skipping winston-logs-display@^0.1.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
111 verbose already installed skipping gulp@^3.8.11 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
112 verbose already installed skipping gulp-concat@^2.2.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
113 verbose already installed skipping gulp-filter@^0.4.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
114 verbose already installed skipping gulp-less@^3.0.3 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
115 verbose already installed skipping gulp-rename@^1.2.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
116 verbose already installed skipping gulp-sourcemaps@^1.5.2 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
117 verbose already installed skipping gulp-typescript@^2.6.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
118 verbose already installed skipping gulp-uglify@^0.3.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
119 verbose already installed skipping gulp-util@^2.2.14 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
120 verbose already installed skipping gulp-webserver@^0.9.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
121 verbose already installed skipping merge2@^0.3.5 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
122 verbose already installed skipping through@^2.3.4 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
123 verbose already installed skipping xmlhttprequest@^1.7.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
124 verbose already installed skipping body-parser@^1.12.3 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
125 verbose already installed skipping cookieparser@^0.1.0 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
126 verbose already installed skipping express@^4.12.3 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
127 verbose already installed skipping express-session@^1.11.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
128 verbose already installed skipping fakeredis@^0.3.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
129 verbose already installed skipping favicon@0.0.2 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
130 verbose already installed skipping jade@^1.9.2 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
131 verbose already installed skipping json@^9.0.3 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
132 verbose already installed skipping logger@0.0.1 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
133 verbose already installed skipping multer@^0.1.8 C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
134 silly install resolved []
135 info build C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
136 info linkStuff vorlon@0.0.14
137 silly linkStuff vorlon@0.0.14 has C:\Users\HCA\Documents\GitHub\vorlonjs as its parent node_modules
138 verbose linkBins vorlon@0.0.14
139 verbose linkMans vorlon@0.0.14
140 verbose rebuildBundles vorlon@0.0.14
141 verbose rebuildBundles [ '.bin',
141 verbose rebuildBundles   'ansi-regex',
141 verbose rebuildBundles   'body-parser',
141 verbose rebuildBundles   'cookieparser',
141 verbose rebuildBundles   'express',
141 verbose rebuildBundles   'express-session',
141 verbose rebuildBundles   'fakeredis',
141 verbose rebuildBundles   'favicon',
141 verbose rebuildBundles   'gulp',
141 verbose rebuildBundles   'gulp-concat',
141 verbose rebuildBundles   'gulp-filter',
141 verbose rebuildBundles   'gulp-less',
141 verbose rebuildBundles   'gulp-rename',
141 verbose rebuildBundles   'gulp-sourcemaps',
141 verbose rebuildBundles   'gulp-typescript',
141 verbose rebuildBundles   'gulp-uglify',
141 verbose rebuildBundles   'gulp-util',
141 verbose rebuildBundles   'gulp-webserver',
141 verbose rebuildBundles   'jade',
141 verbose rebuildBundles   'json',
141 verbose rebuildBundles   'lodash._basecopy',
141 verbose rebuildBundles   'logger',
141 verbose rebuildBundles   'merge2',
141 verbose rebuildBundles   'multer',
141 verbose rebuildBundles   'passport',
141 verbose rebuildBundles   'passport-local',
141 verbose rebuildBundles   'redis',
141 verbose rebuildBundles   'socket.io',
141 verbose rebuildBundles   'socket.io-redis',
141 verbose rebuildBundles   'stylus',
141 verbose rebuildBundles   'through',
141 verbose rebuildBundles   'winston',
141 verbose rebuildBundles   'winston-azure',
141 verbose rebuildBundles   'winston-logs-display',
141 verbose rebuildBundles   'xmlhttprequest' ]
142 verbose rebuild bundle C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\ansi-regex
143 info build C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\ansi-regex
144 info preinstall ansi-regex@1.1.1
145 info linkStuff ansi-regex@1.1.1
146 silly linkStuff ansi-regex@1.1.1 has C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules as its parent node_modules
147 verbose linkBins ansi-regex@1.1.1
148 verbose linkMans ansi-regex@1.1.1
149 verbose rebuildBundles ansi-regex@1.1.1
150 info install ansi-regex@1.1.1
151 info postinstall ansi-regex@1.1.1
152 verbose rebuild bundle C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\lodash._basecopy
153 info build C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules\lodash._basecopy
154 info preinstall lodash._basecopy@3.0.1
155 info linkStuff lodash._basecopy@3.0.1
156 silly linkStuff lodash._basecopy@3.0.1 has C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs\node_modules as its parent node_modules
157 verbose linkBins lodash._basecopy@3.0.1
158 verbose linkMans lodash._basecopy@3.0.1
159 verbose rebuildBundles lodash._basecopy@3.0.1
160 info install lodash._basecopy@3.0.1
161 info postinstall lodash._basecopy@3.0.1
162 info install vorlon@0.0.14
163 info postinstall vorlon@0.0.14
164 info prepublish vorlon@0.0.14
165 verbose unsafe-perm in lifecycle true
166 info vorlon@0.0.14 Failed to exec prepublish script
167 verbose stack Error: vorlon@0.0.14 prepublish: `npm run build`
167 verbose stack Exit status 1
167 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
167 verbose stack     at EventEmitter.emit (events.js:110:17)
167 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
167 verbose stack     at ChildProcess.emit (events.js:110:17)
167 verbose stack     at maybeClose (child_process.js:1015:16)
167 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
168 verbose pkgid vorlon@0.0.14
169 verbose cwd C:\Users\HCA\Documents\GitHub\vorlonjs\Vorlonjs
170 error Windows_NT 6.3.9600
171 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
172 error node v0.12.4
173 error npm  v2.10.1
174 error code ELIFECYCLE
175 error vorlon@0.0.14 prepublish: `npm run build`
175 error Exit status 1
176 error Failed at the vorlon@0.0.14 prepublish script 'npm run build'.
176 error This is most likely a problem with the vorlon package,
176 error not with npm itself.
176 error Tell the author that this fails on your system:
176 error     npm run build
176 error You can get their info via:
176 error     npm owner ls vorlon
176 error There is likely additional logging output above.
177 verbose exit [ 1, true ]

**Comment by cubitouch** [comment]
Should have been specific to my configuration. It's working on a different computer.
